name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Tag Docker Image
        run: |
          docker build -t jvik/elaway-gateway-api:${{ github.event.release.tag_name }} .
          docker tag jvik/elaway-gateway-api:${{ github.event.release.tag_name }} jvik/elaway-gateway-api:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jvik
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push jvik/elaway-gateway-api:${{ github.event.release.tag_name }}
          docker push jvik/elaway-gateway-api:latest
